### ISSUE TITLE
Change the update info format

### ISSUE THREAD

**Issue by se7enf98** [par6n/ncov-19#2]
سلام
برای نمایش ساعت دقیق آخرین به‌روزرسانی بهتره یا از سیستم ۲۴ ساعته استفاده کنین یا سیستم «قبل ظهر/بعد ظهر»
چیزی به اسم «ساعت ۱۴ بعد از ظهر» نداریم :)

**Comment by par6n** [comment]
بله، حق با شماست. با آمار بعدی این مورد رو هم درست می‌کنیم. 
مرسی که اطلاع دادید.
