### ISSUE TITLE
Adding to list

### ISSUE THREAD

**Issue by abuuzayr** [par6n/ncov-19#5]
Hi Ehsaan @par6n ! 

Thank you for this nice app that you built. It gives better perspective of the situation in Iran and it helps that you make it nice as well. 

I'd like to put your app on this list: https://github.com/abuuzayr/coronavirus-apps so i'd just like to know - where are the sources for your data? 

Thanks a lot and God bless you and your team.

**Comment by par6n** [comment]
Hello! It's so nice of you. Our source is the Ministry of Health in Iran and they all come from the official source.

Thank you, and pray we can ride out this storm. :pray:

**Comment by abuuzayr** [comment]
Thank you for the quick reply, I'll put it up now.

Yes, God willing may all of us and our loved ones be safe from this virus!
